package prac.fin.payment.domain.entity;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import prac.fin.payment.common.enums.IntentStatus;
import prac.fin.payment.common.enums.PaymentMethodType;

/**
 * Represents a merchant's intention to collect a specific amount from a customer.
 * One PaymentIntent = one checkout attempt.
 * A single intent can have multiple Transaction records beneath it
 * (e.g. first attempt fails 3DS, customer retries — two transactions, one intent).
 * 
 * IDEMPOTENCY:
 *   idempotencyKey is unique at the database level.
 *   If the merchant retries after a network failure with the same key,
 *   the DB unique constraint catches it before we even run any logic.
 *   We return the existing intent instead of creating a new one.
 *
 * CLIENT SECRET:
 *   Generated by us at creation time. Format: cs_<UUID>.
 *   Passed to the merchant's frontend so it can talk to the checkout page
 *   without the merchant exposing their high-privilege API key to the browser.
 *   Short-lived, only valid while the intent is in REQUIRES_PAYMENT_METHOD.
 * 
 * PROCESSOR REFERENCE:
 *   Null until the payment is sent to Razorpay.
 *   After that, holds Razorpay's payment ID (pay_xxxxxxxxxxxxxxxx).
 *   Used for refunds and reconciliation.
 */
@Entity
@Table(
	name = "payment_intent",
	indexes = {
		// Most queries filter by merchant
		@Index(name = "idx_intent_merchant_id", columnList = "merchant_id"),
		// Idempotency lookup happens on every create request
		@Index(name = "idx_intent_idempotency_key", columnList = "idempotency_key", unique = true),
		// Reconciliation queries filter by status (UNKNOWN, PROCESSING)
		@Index(name = "idx_intent_status", columnList = "status"),
		// Partitioning-style queries: "all intents from today"
		@Index(name = "idx_intent_crated_at", columnList = "created_at")
		
	}
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentIntent extends BaseEntity {

	@Id
	@GeneratedValue
	@Column(name = "id", updatable = false, nullable = false)
	private UUID id;
	
	/**
     * LAZY: JPA will not join to the merchant table unless you
     * explicitly call intent.getMerchant().getSomeField().
     * This keeps single-intent lookups fast.
     */
	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "merchant_id", nullable = false)
	private Merchant merchant;
	
	/**
     * Amount in smallest currency unit (paise for INR, cents for USD).
     * ₹100.00 → stored as 10000.
     */
	@Column(name = "amount", nullable = false)
    private Long amount;
	
	/**
     * ISO 4217 currency code. Exactly 3 uppercase letters.
     * Validated in the service layer against a supported currencies list.
     */
	@Column(name = "currency", nullable = false, length = 3)
    private String currency;
	
	/**
     * Current state in the payment lifecycle.
     */
	@Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 50)
    @Builder.Default
    private IntentStatus status = IntentStatus.REQUIRES_PAYMENT_METHOD;
	
	/**
     * Merchant-generated unique key for this payment attempt.
     * Unique constraint at DB level. The database itself prevents duplicates
     * even under concurrent requests hitting multiple servers simultaneously.
     */
	@Column(name = "idempotency_key", nullable = false, unique = true, length = 255)
    private String idempotencyKey;
	
	@Column(name = "client_secret", nullable = false, updatable = false, length = 100)
    private String clientSecret;
	
	/**
     * Optional at creation — set when the customer picks a payment method
     * on the checkout page, or when the merchant pre-selects one.
     */
	@Enumerated(EnumType.STRING)
    @Column(name = "payment_method_type", length = 30)
    private PaymentMethodType paymentMethodType;
	
	@JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "metadata", columnDefinition = "jsonb")
    @Builder.Default
    private Map<String, Object> metadata = new HashMap<>();
	
	/**
     * Razorpay's payment ID. It is null until the processor call is made.
     * Format: pay_xxxxxxxxxxxxxxxx
     * Set by the processor-service after a successful authorization.
     * Used for: refund requests, reconciliation matching.
     */
	@Column(name = "processor_reference", length = 255)
    private String processorReference;
}
